-- =========================================================
-- MIGRATION 018: Adiciona numero_recebimento à tabela recebimentos
-- Identificador sequencial legível para referência operacional.
-- Usa GENERATED BY DEFAULT AS IDENTITY para permitir backfill.
-- =========================================================

-- Passo 1: Adicionar coluna com GENERATED BY DEFAULT (permite override via UPDATE no backfill)
ALTER TABLE recebimentos
  ADD COLUMN numero_recebimento BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Passo 2: Popular registros existentes em ordem cronológica
WITH ranked AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at ASC, id ASC) AS rn
  FROM recebimentos
)
UPDATE recebimentos r
  SET numero_recebimento = ranked.rn
FROM ranked
WHERE r.id = ranked.id;

-- Passo 3: Ajustar a sequence para continuar a partir do próximo número
SELECT setval(
  pg_get_serial_sequence('recebimentos', 'numero_recebimento'),
  (SELECT MAX(numero_recebimento) FROM recebimentos)
);

-- Passo 4: Tornar NOT NULL após o backfill estar completo
ALTER TABLE recebimentos
  ALTER COLUMN numero_recebimento SET NOT NULL;

-- Passo 5: Índice único para garantir unicidade e performance de busca futura
CREATE UNIQUE INDEX IF NOT EXISTS idx_recebimentos_numero
  ON recebimentos(numero_recebimento);

COMMENT ON COLUMN recebimentos.numero_recebimento IS
  'Identificador sequencial legível para referência operacional (ex: Recebimento #23). Gerado automaticamente.';